### PR TITLE
Add support for CMSIS RTOS

### LINKED ISSUE #160: Handle CMSIS-RTOS and CMSIS-RTOS2 as CMSIS components
Those are included in all CMSIS folder included in hal STM32-HAL it has to be a CMSIS component handled in findCMSIS!

### PR DESCRIPTION
**Pull request by g-arjones**
Closes #160

### CODE REVIEW

**Comment by Hish15** [comment]
The message printing is definitely a good adition!
I don't understand why you had to change the whole looping mechanism, you could handle cmsis like any other cmsis component, on the already existing loop.

Another PR could be made to change the whole looping thing to figure out families first, but I don't think this is linked to what is done on this PR.
Also such a good adition deserve to be added to the Readme 👍

**Comment by g-arjones** [comment]
Please be more specific about what you think is wrong with the "looping mechanism".

I implemented it like the one in the HAL find script is to make it consistent.

Families are, in fact being figured out first (that's what's changed) so I don't really understand what you would like to see in a different PR.

I will gladly at anything to the README as soon as I have any indication that this will ever get merged.

**Comment by Hish15** [comment]
You are right, I was not clear on the "looping mechanism" bit sorry.

It is also true that you did exactly as it's done on the HAL part, so it's perfect.
You did more than just add the feature, and it being a single commit made me misjudge the changes.

**Comment by Hish15** [comment]
Hi @g-arjones,  we are now ready to merge some PR :smile:
Can you add the related documentation so this features become a feature?

Regards,

**Comment by g-arjones** [comment]
@Hish15 Unfortunately, as I mentioned to @atsju I'm now using a fork of this project in production. I have enabled edits by maintainers in all my PRs so you guys are very welcome to modify them as you see fit in case you are interested in the contribution.

**Comment by rmspacefish** [comment]
I added documentation in my fork. I can create a PR if I find some time soon

**Comment by Hish15** [comment]
Closing in favor of #222

**Pull request closed without merging**
