### PR TITLE
added binary and hex generation functions

### PR DESCRIPTION
**Pull request by rmspacefish**
Functions to generate binary file and hex file

### CODE REVIEW

**Comment by gudnimg** [comment]
I think it would be beneficial to add `BYPRODUCTS ${TARGET}.hex` after `COMMAND`.

They mention this in the  docs:
> The Makefile Generators will remove BYPRODUCTS and other GENERATED files during make clean.

I believe the same applies to `ninja clean`.

**Comment by atsju** [comment]
Please update the readme file also.

**Review by atsju — APPROVED** [review]

**Comment by rmspacefish** [comment]
The `${CMAKE_EXECUTABLE_SUFFIX_C}` is needed because the file might or might not have a suffix and the `arm-none-eabi-size` command needs the exact binary name. If the suffix is empty, it's not an issue because the resulting expansion will be empty too

**Comment by gudnimg** [comment]
> The `${CMAKE_EXECUTABLE_SUFFIX_C}` is needed because the file might or might not have a suffix and the `arm-none-eabi-size` command needs the exact executable name. If the suffix is empty, it's not an issue because the resulting expansion will be empty too.

I was not aware of such a limitation. This has worked for me before:

```cmake
# Print size information after build
add_custom_command(TARGET ${target} POST_BUILD
    COMMAND ${CMAKE_SIZE} "${target}"
)
```

`CMAKE_OBJCOPY` is `arm-none-eabi-objcopy`. I know it doesn't need an extension because it worked for me in another project. My executable had no extension such as `.exe`, `.elf`.

I don't quite see yet why `${CMAKE_EXECUTABLE_SUFFIX_C}` is needed with `arm-none-eabi-objcopy` or how that relates to `arm-none-eabi-size`

**Comment by atsju** [comment]
@gudnimg You are right, it's related to #174.
Because every file is formated in some way and I find it good to have the corresponding extension

**Review by Hish15 — APPROVED** [review]

**Pull request merged**
