### PR TITLE
Support STM32U0 Family

### PR DESCRIPTION
**Pull request by xanthio**
Bring STM32U0 family support to project

### CODE REVIEW

**Review by atsju — APPROVED** [review]
I did not check the Flash sizes as I usually do but this looks high quality PR. Thank you.
@Hish15 I let you merge if it's OK for you

**Comment by xanthio** [comment]
> I did not check the Flash sizes as I usually do but this looks high quality PR. Thank you. @Hish15 I let you merge if it's OK for you

Actually, Flash size variants for this family is weird as we can find 16/32/64M of Flash but it depends the package:
    U031C6
    U031C8
    U031F4
    U031F6
    U031F8
    U031G6
    U031G8
    U031K4
    U031K8
    U031R6
    U031R8

Do you think there is an interest in splitting this subfamilly ?

**Comment by atsju** [comment]
I checked your code is actually correct. 
example: U031C6 => U031 gives RAM size because is a specific subfamily and here all the subfamily has same RAM (cool, not always the case)  
C => package => no interrest for us in this case. Sometimes it has an effect  
6 => flash size. See file common.cmake

**Comment by xanthio** [comment]
@Hish15 Is there an issue for not merging this PR ?

I'm starting a project with STM32U0 target and would really like to submodule this before.

**Comment by Hish15** [comment]
Seems good to me, solve the conflict and we are good to go!

**Review by Hish15 — APPROVED** [review]

**Pull request merged**
