### PR TITLE
Update versions: Cube, CMSIS, and HAL

### LINKED ISSUE #217: Update CMSIS, HAL and Cube
There are updates available. Some minor, some major. 

I am creating this issue more as a reminder for me to create a PR or if someone wants do it before me :)

### PR DESCRIPTION
**Pull request by gudnimg**
Updated to latest as of 22. June 2021 for all families

Resolves #217

### CODE REVIEW

**Comment by atsju** [comment]
Close re-open to trigger automated tests

**Comment by atsju** [comment]
@gudnimg Thank you for your contribution. Please consider looking at failing test and fixing it. Obviously there has been a big change in some HAL preventing build with current examples.

This failed test proves that it will be very difficult to validate your change because there may be other hidden bugs that are unseen by this quick tests. I am ready to merge the change because it's an improvement BUT the correct solution would be to be able to fetch "latest" version of STM32 repository or a given one given by user and not by us (stm32-cmake).  Because users need to be master of what they fetch, the version shall not depend on this repo.

**Comment by gudnimg** [comment]
I was able to replicate the failed test. I fixed it by replacing the contents of https://github.com/ObKo/stm32-cmake/blob/master/tests/hal/stm32h7xx_hal_conf.h with the contents provided here https://github.com/STMicroelectronics/stm32h7xx_hal_driver/blob/master/Inc/stm32h7xx_hal_conf_template.h

There are small differences but enough to solve the issue on my end. It is not immediately obvious to me where `stm32h7xx_hal_conf.h `comes in. We should try to use the one pulled by git in my opinion to stay up to date with version changes.

**Comment by gudnimg** [comment]
I've updated the rest of the stm32xxxx_hal_conf.h files to keep everything up to date. The configuration files which are not modified in this PR are still up to date.

**Comment by gudnimg** [comment]
I had to disable the following new configuration for the G0 series due to a bug: https://github.com/STMicroelectronics/STM32CubeG0/issues/13

```c
// #define HAL_HCD_MODULE_ENABLED
```

**Review by atsju — APPROVED** [review]

**Review by Hish15 — APPROVED** [review]

**Pull request merged**
