### PR TITLE
Duplicate blinky C version as C++ example

### PR DESCRIPTION
**Pull request by Osteri**
As discussed with @Hish15 and @atsju in #274, adding an C++ example would be nice for newcomers. 

So here it is.

Only difference compared to `blinky.c`:
```cpp
extern "C" {
  void SysTick_Handler();
}
```
Tested with F4.

### CODE REVIEW

**Comment by Hish15** [comment]
This does duplicate a lot of things...

I think it's better to just write a blinky.cpp file, then give the option to use or not C++ on the CMakeLists file.

Another approach would be to create a file `system_config.c`, move the `SysTick_Handler` definition there, and then state in the CmakeLists, or blinky file, that it's possible to make blink.c ->blinky.cpp  and get thing running flawlessly.

A third approch is not to have this example depend on interrupt, no need to redefine `SysTick_Handler` once again.

What do you guys think? (@Osteri and @atsju)

**Comment by atsju** [comment]
I'm against 3rd option as it would remove some knowledge from the already simple example.

Having blinky.c compiles in C++ or C depending on Cmake or on extension seems good.
You could do a blinky.h file to have the `extern C` on declaration in .h and not on definition in .c/.cpp but this is matter of taste.

**Comment by Osteri** [comment]
To clarify: we would like to have separate blinky.cpp and blinky.c in blinky example folder and then based on some switches interselect between them during the compilation phase?

> then give the option to use or not C++ on the CMakeLists file.

What kind of option? Best option IMO is the project definiton `project(stm32-blinky CXX C ASM)`. If we derive this option somehow and customize based on that we can reflect "is this a C++ or C pure project?".

> Having blinky.c compiles in C++ or C depending on Cmake or on extension seems good.

I think CMake uses file extension to define how to compile the current file (it selects C or C++ compiler depending on the file extension). So it makes more sense IMO that we have different `blinky.cpp` for C++ and `blinky.c` for C compared to `blinky.c` which we would either compile to C++ or C.

**Comment by Hish15** [comment]
When I say option, I mean cmake option as seen here https://github.com/ObKo/stm32-cmake/blob/2dc0456bc5317a467ea25fc4d36dbc8e2178bdee/examples/blinky/CMakeLists.txt#L8

Having blinky.c and blinky.cpp and adding one or the over using target_sources(), and the previously defined option is the way to go yes. This option can be used to define le project conditionally too.

**Comment by atsju** [comment]
close in favor of #285

**Pull request closed without merging**
